### ISSUE TITLE
Expiry Date Problem

### ISSUE THREAD

**Issue by JayedHasan232** [brendanbond/react-acceptjs#1]
Always showing { code: "E_WC_07", text: "**Please provide valid expiration year.**" } and { code: "E_WC_06", text: "**Please provide valid expiration month.**" } errors.

Please help me.

**Comment by brendanbond** [comment]
Hi @JayedHasan232, let's try to get to the bottom of this. How are you using the library? In other words, are you using the hook, the <HostedForm/> component, or the <AcceptHosted /> component?

**Comment by brendanbond** [comment]
@JayedHasan232 any updates?

**Comment by JayedHasan232** [comment]
@brendanbond I'll let you know after a new try. Thank your for your response.

**Comment by JayedHasan232** [comment]
At first, I am using **react@"^17.0.2"** and the package is requiring **react@"^16.0.0"**. So, if I install it by adding **--force** or **--legacy-peer-deps**, it's installing but showing errors.

**Comment by brendanbond** [comment]
@JayedHasan232 React is a peer dependency of this library, so it should just give you a warning and install just fine. I'll update the package.json to include ^17.0.0, but you're saying you're running into errors on install? You shouldn't have to use --force or --legacy-peer-deps

**Comment by JayedHasan232** [comment]
It was the main error. I have changed "expMonth" and "expYear" to "month" and "year". It fixed now.

<img width="1080" alt="Screenshot 2021-12-09 at 10 30 43 PM" src="https://user-images.githubusercontent.com/60888930/145437064-2df09491-a68b-47d1-a6ae-1e879dfe1ec0.png">

**Comment by brendanbond** [comment]
Great! I'll change the docs, the Authorize.net types are 'month' and 'year', I should make that clearer.

**Comment by brendanbond** [comment]
@JayedHasan232 I'm not sure yet how to mention new merges in comments, but I've fixed your issue in version 0.2.0, the types should be fixed in the docs! Thanks for your help here

**Comment by JayedHasan232** [comment]
You are most welcome and thanks a lot for your **effort**. **Go ahead.**
